<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6b36f170-e37a-4c76-8d32-8ddbb00b6223</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Testes\**" />
    <Content Remove="Testes\**" />
    <EmbeddedResource Remove="Testes\**" />
    <None Remove="Testes\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlataformaVendas.Dominio\PlataformaVendas.Dominio.csproj" />
    <ProjectReference Include="..\PlataformaVendas.Ioc\PlataformaVendas.Infra.csproj" />
  </ItemGroup>

</Project>
